services:
    erp-axion-api:
        container_name: erp-axion-api
        build: . 
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - erp_db

    erp_db:
        image: postgres:15
        container_name: erp-db
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: erp_database
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: